version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php 