services:
  php:
    build: .
    volumes:
      - .:/var/www

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  sqlite:
    image: keinos/sqlite3
    volumes:
      - ./var:/var/www/var 