version: '3.8'

services:
  php:
    build: .
    volumes:
      - .:/var/www
      - ./var:/var/www/var
    env_file:
      - .env.docker
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  sqlite:
    image: keinos/sqlite3
    volumes:
      - ./var:/var/www/var
    command: tail -f /dev/null 